name: PRIME_LLM
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _openmp_mutex=4.5=3_kmp_llvm
  - _py-xgboost-mutex=2.0=cpu_0
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=2.1.0=pyhd8ed1ab_0
  - accelerate=1.0.1=pyhd8ed1ab_0
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h2019614_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alembic=1.14.0=pyhd8ed1ab_0
  - arrow-cpp=9.0.0=py38h709d5f2_2_cpu
  - astor=0.8.1=pyh9f0ad1d_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_2
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-cal=0.5.11=h95a6274_0
  - aws-c-common=0.6.2=h27cfd23_0
  - aws-c-event-stream=0.2.7=h3541f99_13
  - aws-c-io=0.10.5=hfb6a706_0
  - aws-checksums=0.1.11=ha31a3da_7
  - aws-sdk-cpp=1.8.186=hecaee15_4
  - backcall=0.2.0=pyh9f0ad1d_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=mkl
  - blas-devel=3.9.0=12_linux64_mkl
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli=1.0.9=h5eee18b_9
  - brotli-bin=1.0.9=h5eee18b_9
  - brotli-python=1.0.9=py38hfa26641_8
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorlog=6.9.0=pyh707e725_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cryptography=39.0.0=py38h1724139_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=11.8=hcce14f8_3
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=1.18.3=pyhd8ed1ab_0
  - debugpy=1.8.5=py38h6d02427_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.9=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - flatbuffers=25.1.21=h8f4948b_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.4.1=py38h01eb140_0
  - fsspec=2024.10.0=pyhff2d567_0
  - gast=0.4.0=pyh9f0ad1d_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - greenlet=3.0.3=py38h17151c0_0
  - grpc-cpp=1.46.4=h6fc47f4_3
  - grpcio=1.46.3=py38ha0cdfde_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.9.0=nompi_py38h89e2d6c_100
  - hdf5=1.14.0=nompi_h5231ba7_103
  - hpack=4.0.0=pyh9f0ad1d_0
  - huggingface_hub=0.26.5=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=58.2=he6710b0_3
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py38h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - keras=2.11.0=py38h06a4308_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20211102.0=cxx17_h48a1fff_3
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcblas=3.9.0=12_linux64_mkl
  - libcrc32c=1.1.2=h6a678d5_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=7.87.0=h6312ad2_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libgoogle-cloud=1.40.2=hefc27d0_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.16.0=h491838f_2
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxgboost=2.1.1=h6a678d5_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - mako=1.3.5=pyhd8ed1ab_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-devel=2021.4.0=ha770c72_730
  - mkl-include=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py38h06a4308_0
  - multidict=6.0.5=py38h01eb140_0
  - multiprocess=0.70.16=py38h01eb140_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openblas=0.3.28=pthreads_h6ec200e_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=1.1.1w=hd590300_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - optuna=4.3.0=pyhd8ed1ab_0
  - orc=1.7.6=h6c59b99_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.0.3=py38h01efb38_1
  - parquet-cpp=1.5.1=2
  - parso=0.8.4=pyhd8ed1ab_0
  - peft=0.13.2=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - protobuf=3.20.3=py38h6a678d5_0
  - psutil=5.9.0=py38h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-xgboost=2.1.1=py38h06a4308_0
  - pyarrow=9.0.0=py38h440d56e_2_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.15=h257c98d_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=py38h06a4308_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python-xxhash=3.5.0=py38h2019614_0
  - python_abi=3.8=7_cp38
  - pytorch=2.3.0=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.2=py38h2019614_0
  - pyzmq=26.2.0=py38h6c80b9a_0
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8c095d6_2
  - regex=2024.7.24=py38h2019614_0
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - s2n=1.0.10=h9b69904_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - safetensors=0.4.4=py38h4005ec7_0
  - scikit-learn=1.3.2=py38ha25d942_2
  - scipy=1.10.1=py38h14f4228_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlalchemy=2.0.32=py38h2019614_0
  - sqlite=3.46.0=h6d4b2fc_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.13.3=py38h06a4308_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.7.0=h924138e_0
  - tensorboard=2.11.0=py38h06a4308_0
  - tensorboard-data-server=0.6.1=py38h2b5fc30_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.11.0=mkl_py38hda6d4db_0
  - tensorflow-base=2.11.0=mkl_py38he5f8e37_0
  - tensorflow-estimator=2.11.0=py38h06a4308_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.3.0=py38_cu118
  - torchtriton=2.3.0=cuda123py38hdb19cb5_0
  - torchvision=0.18.0=py38_cu118
  - tornado=6.4.1=py38hfb59056_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.6=pyhd8ed1ab_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - wrapt=1.16.0=py38h01eb140_0
  - xgboost=2.1.1=py38h06a4308_0
  - xxhash=0.8.2=hd590300_0
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py38h01eb140_0
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.5.6=hc292b87_0
  - pip:
      - tokenizers==0.20.3
      - transformers==4.46.3