data: "/path/to/X.pt"
target: "/path/to/y.pt"
time_seq: "/path/to/time_sequence.pt"
time_seq_offset: 1
optim_size: 1000
val_size: 200

res_dir: "./results/"
tmp_dir: "./tmp/"
suffix: "lstm_experiment"

batch_size: 16
n_trials: 40
n_resamples: 5
epochs: 40
patience: 5

best_params: null        # path to best params .pkl or null to run BO
train_size: "50,100,200"
num_classes: null
seed: 93