data: "path/to/preprocessed_data_list.npy"
columns: "path/to/columns.npy"
columns_numeric: "path/to/col/num.npy"
columns_numeric_missing: "path/to/col/num/mis.npy"
columns_discrete: "path/to/col/dis.npy"
columns_discrete_missing: "path/to/col/dis/mis.npy"
target_related_columns: "path/to/target_related_col.npy"
target_name: "target_variable_name"
output_dir: "path/to/outputs/"