preprocess:
  data: "path/to/data.csv"
  var: "path/to/var.csv"
  res_dir: "path/to/results/"
  suffix: "suffix_value"

make_zero_padding:
  data: "path/to/preprocessed_data.npy"
  columns: "path/to/columns.npy"
  num_col: "path/to/num_col.npy"
  mis_num_col: "path/to/mis_num_col.npy"
  dis_col: "path/to/dis_col.npy"
  mis_dis_col: "path/to/mis_dis_col.npy"
  seq_len: 100
  res_dir: "path/to/results/"
  suffix: "suffix_value"

make_input:
  min_seq_len: 10
  max_seq_len: 50
  col_names: "/path/to/data_columns.npy"
  num_col_names: "/path/to/columns_numeric.npy"
  mis_num_col_names: "/path/to/columns_numeric_missing.npy"
  dis_col_names: "/path/to/columns_discrete.npy"
  mis_dis_col_names: "/path/to/columns_discrete_missing.npy"
  data: "path/to/padded_data.npy"
  pat_inf: "path/to/pat_inf.npy"
  target_related_col: "/var/jupyterhub/ldl_related_columns.npy"
  target_col: 46
  mis_target_col: 746
  target_name: "ldl"
  subset: 20000
  make_sliding_windows: true # Whether to make slidding windows or not
  max_prediction_window: 5  # If make_slidding_windows==true, set the max number of time points spanning the prediction window
  remove_rows: 0     # If make_slidding_windows==true, where is the prediction point relative to the target point (0 for immdiately before, 1 two timepoints before and so on)
  res_dir: "/path/to/results"
  suffix: "ldl_suffix"